### ISSUE TITLE
aggiungere ultimi plot al file plots.py

### ISSUE THREAD

**Issue by alessioarcudi** [alessioarcudi/ExIFFI#3]
come fatto con gli score plot e bar plot mettere pure le importance maps e il complete maps sul file plot.py 
semplificando l'input ai minimi elementi necessari (guardre le altre due funzioni se necessario

**Comment by alessioarcudi** [comment]
lavora nella branch plots!

**Comment by FrizzoDavide** [comment]
Ok ho inserito i plot nello script `plot.py`. Gli ho anche testati con `wine` e funzionano come atteso. Ho già committato tutto

**Comment by FrizzoDavide** [comment]
Quindi credo di poter chiudere la Issue
